### ISSUE TITLE
有个疑问？

### ISSUE THREAD

**Issue by Omooo** [121880399/LargeImageMonitor#2]
不能带到线上就有点不够刺激了。
很多图片是市场部配的，我们开发中 mock 的图片数据其实没有多大的意义去监控大小。
所以感觉还是得带到线上去看的。

**Comment by 121880399** [comment]
> 不能带到线上就有点不够刺激了。
> 很多图片是市场部配的，我们开发中 mock 的图片数据其实没有多大的意义去监控大小。
> 所以感觉还是得带到线上去看的。

带线上去也可以，但是要考虑以什么形式返回和预警，上报到APM系统还是怎么的。
